services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always

  weather-app:
    build:
      context: .
      args:
        WEATHER_API_KEY: ${WEATHER_API_KEY}
    ports:
      - "8080:8080"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - SPRING_REDIS_HOST=redis